### ISSUE TITLE
Если у тебя переменная хранит массив, назови ее множественным числом. Будет проще воспринимать.

### ISSUE THREAD

**Issue by pekhota** [ViktorOrda/PHP-school#2]
https://github.com/ViktorOrda/PHP-school/blob/9fad4c749e01341ae606404cda4014131bc269de/lesson6/homework.php#L23

**Comment by ViktorOrda** [comment]
Fixed in https://github.com/ViktorOrda/PHP-school/commit/d2d614107d87661fbf395d438c4d8cc35445b037
