### ISSUE TITLE
Валидацию подобного рода лучше вынести в отдельные методы.

### ISSUE THREAD

**Issue by pekhota** [ViktorOrda/PHP-school#3]
https://github.com/ViktorOrda/PHP-school/blob/9fad4c749e01341ae606404cda4014131bc269de/lesson6/homework.php#L29

**Comment by ViktorOrda** [comment]
Fixed in https://github.com/ViktorOrda/PHP-school/commit/7102cc0a9f691feabf24d1524dfe581143297814
